use egui::Key;
use tk_pie::button::Button;
use tk_pie::keys::Key as K;

macro_rules! k {
    ($k: ident) => {
        Button::Key(K::$k)
    };
}

pub fn map_key(key: &Key) -> Option<Button> {
    Some(match key {
        Key::ArrowDown => k!(DownArrow),
        Key::ArrowLeft => k!(LeftArrow),
        Key::ArrowRight => k!(RightArrow),
        Key::ArrowUp => k!(UpArrow),
        Key::Escape => k!(Escape),
        Key::Tab => k!(Tab),
        Key::Backspace => k!(Backspace),
        Key::Enter => k!(Return),
        Key::Space => k!(Space),
        Key::Insert => k!(Insert),
        Key::Delete => k!(Delete),
        Key::Home => k!(Home),
        Key::End => k!(End),
        Key::PageUp => k!(PageUp),
        Key::PageDown => k!(PageDown),
        Key::Colon => k!(Colon),
        Key::Comma => k!(Comma),
        Key::Backslash => k!(BackslashPipe),
        Key::Slash => k!(Slash),
        Key::Pipe => k!(BackslashPipe),
        Key::OpenBracket => k!(LBracket),
        Key::CloseBracket => k!(RBracket),
        Key::Minus => k!(Dash),
        Key::Period => k!(Period),
        Key::Plus => k!(KeypadPlus),
        Key::Equals => k!(Equal),
        Key::Semicolon => k!(Colon),
        Key::Quote => k!(Apostrophe),
        Key::Questionmark => k!(Slash),
        Key::Backtick => k!(Accent),
        Key::Num0 => k!(D0),
        Key::Num1 => k!(D1),
        Key::Num2 => k!(D2),
        Key::Num3 => k!(D3),
        Key::Num4 => k!(D4),
        Key::Num5 => k!(D5),
        Key::Num6 => k!(D6),
        Key::Num7 => k!(D7),
        Key::Num8 => k!(D8),
        Key::Num9 => k!(D9),
        Key::A => k!(A),
        Key::B => k!(B),
        Key::C => k!(C),
        Key::D => k!(D),
        Key::E => k!(E),
        Key::F => k!(F),
        Key::G => k!(G),
        Key::H => k!(H),
        Key::I => k!(I),
        Key::J => k!(J),
        Key::K => k!(K),
        Key::L => k!(L),
        Key::M => k!(M),
        Key::N => k!(N),
        Key::O => k!(O),
        Key::P => k!(P),
        Key::Q => k!(Q),
        Key::R => k!(R),
        Key::S => k!(S),
        Key::T => k!(T),
        Key::U => k!(U),
        Key::V => k!(V),
        Key::W => k!(W),
        Key::X => k!(X),
        Key::Y => k!(Y),
        Key::Z => k!(Z),
        Key::F1 => k!(F1),
        Key::F2 => k!(F2),
        Key::F3 => k!(F3),
        Key::F4 => k!(F4),
        Key::F5 => k!(F5),
        Key::F6 => k!(F6),
        Key::F7 => k!(F7),
        Key::F8 => k!(F8),
        Key::F9 => k!(F9),
        Key::F10 => k!(F10),
        Key::F11 => k!(F11),
        Key::F12 => k!(F12),
        Key::F13 => k!(F13),
        Key::F14 => k!(F14),
        Key::F15 => k!(F15),
        Key::F16 => k!(F16),
        Key::F17 => k!(F17),
        Key::F18 => k!(F18),
        Key::F19 => k!(F19),
        Key::F20 => k!(F20),
        Key::F21 => k!(F21),
        Key::F22 => k!(F22),
        Key::F23 => k!(F23),
        Key::F24 => k!(F24),

        key => {
            log::warn!("Unsupported character {key:?}");
            return None;
        }
    })
}
