[package]
name = "tangentbord1-left"
version = "0.1.0"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]
description = "Keyboard firmware"
edition = "2021"

[dependencies.tangentbord1]
path = "../lib"
package = "tangentbord1-lib"

[target.thumbv6m-none-eabi.dependencies]
cortex-m-rt = "0.7"
embassy-rp = { version = "0.1.0", features = ["time-driver", "critical-section-impl"] }
embassy-executor = { version = "0.5.0", features = ["nightly", "executor-thread", "integrated-timers", "arch-cortex-m"] }
embassy-sync = "0.5.0"
embassy-time = "0.3.0"
embassy-futures = "0.1.1"
log = "0.4.17"
postcard = { version = "1.0.4", features = ["alloc"] }

[build-dependencies]
ron = "0.8.0"
postcard = { version = "1", features = ["use-std"] }

[build-dependencies.tangentbord1]
path = "../lib"
package = "tangentbord1-lib"
